name: CD Pipeline

on:
  workflow_run:
    workflows: ['Docker Image CI']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull smw0807/pubg-api:1.0.0
      - name: Delete Old docker container
        run: sudo docker rm -f pubg-api-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name pubg-api-container smw0807/pubg-api:1.0.0
