name: CD

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: DockerHub Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Pull latest image
        run: docker pull smw0807/pubg-api:1.0.0

      - name: Stop and remove old container
        run: |
          docker stop pubg-api || true
          docker rm pubg-api || true

      - name: Run new container
        run: |
          docker run -d \
            --name pubg-api \
            --env-file /home/ubuntu/app/.env \
            --restart always \
            -p 3000:3000 \
            smw0807/pubg-api:1.0.0
